[package]
name = "swfcompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core dependencies
flate2 = {version = "1.0"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swf = { git = "https://github.com/ruffle-rs/ruffle" }
image = "0.24.6"

# gui dependencies
clap = { version = "4.3.0", features = ["derive"] }
egui = "0.22.0"
egui-wgpu = { version = "0.22.0", features = ["winit"] }
egui-winit = "0.22.0"
ruffle_render = { git = "https://github.com/ruffle-rs/ruffle", features = ["clap"] }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle", features = ["clap"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
generational-arena = "0.2.8"
tracing = "0.1.37"
winit = "0.28.6"
webbrowser = "0.8.10"
url = "2.3.1"
arboard = "3.2.0"
dirs = "5.0"
isahc = "1.7.2"
rfd = "0.11.4"
anyhow = "1.0"
bytemuck = "1.13.1"
os_info = { version = "3", default-features = false }
unic-langid = "0.9.1"
sys-locale = "0.3.0"
wgpu = { version = "0.16.0" }
futures = "0.3.28"
chrono = { version = "0.4", default-features = false, features = [] }
fluent-templates = "0.8.0"

# Deliberately held back to match tracy client used by profiling crate
tracing-tracy = { version = "=0.10.0", optional = true }

[build-dependencies]
embed-resource = "2"
vergen = { version = "8.2.0", features = ["build", "git", "gitcl", "cargo"] }

